build:
  tags: [Linux, shell_executor]
  script:
    - mkdir output
    - podman login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin <<<"$CI_REGISTRY_PASSWORD"
    - go run breadmaker.go --all
  artifacts:
    paths:
      - output/*.log
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
