name: build
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Generate Bake definition file
        run: find * -name Dockerfile | ./knead > docker-bake.json

      - name: Build and push to Docker Hub
        uses: docker/bake-action@v1.6.0
        with:
          push: true
          set: |
            *.cache-from=type=local,src=/tmp/buildx_cache
            *.cache-to=type=local,dest=/tmp/buildx_cache_new

        # buildx has to write from some "old cache" to some "new cache"
        # https://github.com/docker/build-push-action/issues/252
      - name: Move cache
        run: |
          rm -rf /tmp/buildx_cache
          mv /tmp/buildx_cache_new /tmp/buildx_cache
