name: build
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # checkout the whole repo history
          fetch-depth: 0

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Generate Bake definition file
        run: >
          git diff --name-only ${{ github.event.before }}..${{ github.event.after }}
          | grep '/Dockerfile$'
          | ./knead
        continue-on-error: true  # fails when no Dockerfiles have changed

      - name: Build and push to Docker Hub
        if: steps.knead.conclusion == 'success'  # don't run if no Dockerfiles have changed
        uses: docker/bake-action@v1.6.0
        with:
          push: true
